# Generated by Django 5.1.1 on 2026-06-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_group_post_group_follow"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"default_related_name": "%(class)s"},
        ),
        migrations.AlterModelOptions(
            name="follow",
            options={"default_related_name": "%(class)s"},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"default_related_name": "%(class)s"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"default_related_name": "%(class)s", "ordering": ["-pub_date"]},
        ),
    ]
